spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url : jdbc:postgresql://localhost:5433/postgres
    #username: postgres
    #password: postgres
    url : ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: NEVER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: salesforce
      #hibernate.id.new_generator_mappings: true
server :
     port : 8080